[project]
name = "momentum"
version = "1.0.0"
description = "A light-weight task tracking application"
requires-python = ">=3.12"
dependencies = [
  "flask>=3.1.2",
  "flask-cors>=6.0.2",
  "flask-sqlalchemy>=3.1.1"
]

[dependency-groups]
dev = [
  "black>=26.1.0",
  "pytest>=9.0.2",
  "pytest-flask>=1.3.0",
  "ruff>=0.14.14"
]